//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGalleryAPIData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eContact_Cendyn_TeamDevEntities : DbContext
    {
        public eContact_Cendyn_TeamDevEntities()
            : base("name=eContact_Cendyn_TeamDevEntities")
        {
        }
    
        public virtual DbSet<eContact_Settings> eContact_Settings { get; set; }
    }
}
