//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGalleryAPIData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyName_Other { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> ParentCompany { get; set; }
        public string CompanyLogo { get; set; }
        public string WebSite { get; set; }
        public string DBString { get; set; }
        public string DBString_eConcierge { get; set; }
        public string VisitorIntelligence { get; set; }
        public string ROIReport { get; set; }
        public Nullable<bool> SendDirect { get; set; }
        public Nullable<bool> GetCC { get; set; }
        public string NoticeEmail { get; set; }
        public string ProjectEmailBcc { get; set; }
        public string Directory { get; set; }
        public string SiteAdminLink { get; set; }
        public Nullable<int> TimeSheetProjectID { get; set; }
        public string TimeSheetProjectList { get; set; }
        public Nullable<bool> HasSiteEditing { get; set; }
        public Nullable<bool> HasEventCalendar { get; set; }
        public Nullable<bool> HasBookEngine { get; set; }
        public Nullable<bool> HasConcierge { get; set; }
        public Nullable<bool> HasOnlineRetail { get; set; }
        public Nullable<bool> DynamicRecipient { get; set; }
        public Nullable<bool> HasForms { get; set; }
        public Nullable<bool> HasBlog { get; set; }
        public string AvailSecurityGroup { get; set; }
        public Nullable<bool> HasMemberArea { get; set; }
        public string ProjectWebFolder { get; set; }
        public Nullable<bool> HasMetaSiteEditing { get; set; }
        public Nullable<bool> HasSiteEAdmin { get; set; }
        public Nullable<bool> HaseGoogleAnalytics { get; set; }
        public Nullable<bool> HasConciergeAdmin { get; set; }
        public Nullable<bool> HaseCalednar { get; set; }
        public Nullable<bool> HaseGallery { get; set; }
        public Nullable<bool> HaseCommerce { get; set; }
        public Nullable<bool> HaseInsight { get; set; }
        public Nullable<bool> HasBuildTemplate { get; set; }
        public Nullable<bool> HasBounceEmail { get; set; }
        public Nullable<bool> HaseMenu { get; set; }
        public string eMenuFolderPath { get; set; }
        public Nullable<bool> HaseBookerReport { get; set; }
        public string eBookerReportPath { get; set; }
        public Nullable<bool> HaseContact { get; set; }
        public string eContactFolderPath { get; set; }
        public Nullable<bool> HasTravelScream { get; set; }
        public Nullable<bool> HaseIcePortal { get; set; }
        public Nullable<bool> HasDNN { get; set; }
        public Nullable<bool> ServiceHold { get; set; }
        public Nullable<bool> SendNotifyEmail { get; set; }
        public Nullable<bool> SpecialTemplate { get; set; }
        public int ListrakProductionID { get; set; }
        public int ListrakReviewID { get; set; }
        public int ListrakSuppressionListID { get; set; }
        public string ClientType { get; set; }
        public Nullable<int> ID_Web_Intranet { get; set; }
        public string eGallery_eContact { get; set; }
        public string eCom_username { get; set; }
        public string eCom_password { get; set; }
        public string eCom_password2 { get; set; }
        public string eCom_admin_username { get; set; }
        public string eCom_admin_password { get; set; }
        public string eCom_admin_password2 { get; set; }
        public string eInsight_PropertyCode { get; set; }
        public Nullable<bool> IseInsightCorp { get; set; }
    }
}
